config/routes.rb
Rails.application.routes.draw do
  resources :job_posts do 
    collection do 
      get :show_contractor_job
    end
  end

  root to: "welcome#index"

  get '/search', to: "job_posts#search"
  
  devise_for :users
  
  resources :users
  resources :contractors
  resources :workers
  resources :applies   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apply.rb
class Apply < ApplicationRecord
	belongs_to :worker
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_apply, only: %i[ show edit update destroy ]

  # GET /applies or /applies.json
  def index
    @applies = Apply.all
  end

  # GET /applies/1 or /applies/1.json
  def show
  end

  # GET /applies/new
  def new
    @apply = Apply.new
  end

  # GET /applies/1/edit
  def edit
  end

  # POST /applies or /applies.json
  def create
    @apply = Apply.new(apply_params)
    @apply.worker_id = current_user.id
    respond_to do |format|
      if @apply.save
        format.html { redirect_to @apply, notice: "User Apply  successfully ." }
        format.json { render :show, status: :created, location: @apply }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applies/1 or /applies/1.json
  def update
    respond_to do |format|
      if @apply.update(apply_params)
        format.html { redirect_to @apply, notice: "Apply was successfully updated." }
        format.json { render :show, status: :ok, location: @apply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applies/1 or /applies/1.json
  def destroy
    @apply.destroy
    respond_to do |format|
      format.html { redirect_to applies_url, notice: "Apply was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apply
      @apply = Apply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apply_params
      params.require(:apply).permit(:name, :contact, :experience, :expectedSalary, :worker_id)
    end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/_form.html.erb
<%= form_with(model: apply, local: true) do |form| %>
  <% if apply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apply.errors.count, "error") %> prohibited this apply from being saved:</h2>

      <ul>
      <% apply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact%>
    <%= form.number_field :contact %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.label :expectedSalary %>
    <%= form.number_field :expectedSalary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applies/edit.html.erb
<h1>Editing Apply</h1>

<%= render 'form', apply: @apply %>

<%= link_to 'Show', @apply %> |
<%= link_to 'Back', applies_path %>

app/views/applies/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Apply for job</h1>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact-no</th>
      <th>Experience</th>
      <th>Expected-salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applies.each do |apply| %>
     <% if apply.worker == current_user %>
      <tr>
        <td><%= apply.name %></td>
        <td><%= apply.contact %></td>
        <td><%= apply.experience %></td>
        <td><%= apply.expectedSalary %></td>
        <td><%= link_to 'Show', apply %></td>
        <td><%= link_to 'Edit', edit_apply_path(apply) %></td>
        <td><%= link_to 'Cancel', apply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Apply for job', new_apply_path %>
<br>
<%= link_to 'Back', job_posts_path %>

app/views/applies/new.html.erb
<h1>New Apply</h1>

<%= render 'form', apply: @apply %>

<%= link_to 'Back', applies_path %>

app/views/applies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apply.name %>
</p>

<p>
  <strong>Contact-no:</strong>
  <%= @apply.contact %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @apply.experience %>
</p>

<p>
  <strong>Expected-salary:</strong>
  <%= @apply.expectedSalary %>
</p>
<p>
  <strong>Worker:</strong>
  <%= @apply.worker_id %>
</p>


<%= link_to 'Edit', edit_apply_path(@apply) %> |
<%= link_to 'Back', applies_path %>