config/routes.rb
Rails.application.routes.draw do
  resources :job_posts do 
    collection do 
      get :show_contractor_job
    end
  end

  root to: "welcome#index"

  get '/search', to: "job_posts#search"
  
  devise_for :users
  
  resources :users
  resources :contractors
  resources :workers
  resources :applies   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job_post.rb
class JobPost < ApplicationRecord
	belongs_to :contractor
	validates :title, :contact, :presence =>true
	
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_job_post, only: %i[ show edit update destroy ]


# GET /job_posts or /job_posts.json
  def index
    @job_posts = JobPost.all
  end

  # GET /job_posts/1 or /job_posts/1.json
  def show
  end

  # GET /job_posts/new
  def new
    @job_post = JobPost.new
    #@job_post = current_user.job_posts.build
  end

  # GET /job_posts/1/edit
  def edit
  end

  # Get /Search data
  def search
     @job_posts = JobPost.where("title LIKE ?","%"+ params[:title] +"%")
      if @job_posts.present?
         render "index"
      else
        flash.alert = "Title not found"
        redirect_to job_posts_path
      end
  end

  def show_contractor_job
    @job_posts = JobPost.all
  end

  
  # POST /job_posts or /job_posts.json
  def create
    @job_post = JobPost.new(job_post_params)
    @job_post.contractor_id = current_user.id

    respond_to do |format|
      if @job_post.save
        format.html { redirect_to @job_post, notice: "Job post was successfully created." }
        format.json { render :show, status: :created, location: @job_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /job_posts/1 or /job_posts/1.json
  def update
    respond_to do |format|
      if @job_post.update(job_post_params)
        format.html { redirect_to @job_post, notice: "Job post was successfully updated." }
        format.json { render :show, status: :ok, location: @job_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_posts/1 or /job_posts/1.json
  def destroy
    @job_post.destroy
    respond_to do |format|
      format.html { redirect_to job_posts_url, notice: "Job post was successfully destroyed." }
      format.json { head :no_content }
    end
  end


 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_post_params
      params.require(:job_post).permit(:title,:description, :contact, :salary, :contractor_id)
    end
  end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
 
<%= form_with(model: job_post,local: true) do |form| %>
  <% if job_post && job_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_post.errors.count, "error") %> prohibited this apply from being saved:</h2>

      <ul>
      <% job_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.number_field :contact %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_posts/edit.html.erb
<h1>Editing Job Post</h1>

<%= render 'form', job_post: @job_post %>

<%= link_to 'Show', @job_post %> |
<%= link_to 'Back', show_contractor_job_job_posts_path  %>

app/views/job_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Posts</h1>

<table>
  <thead>
    <tr>
       <th>Title</th>
      <th>Description</th>
      <th>Contact</th>
      <th>Salary</th>
       <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_posts.each do |job_post| %>
    <tr>
        <td><%= job_post.title %></td>
        <td><%= job_post.description %></td>
        <td><%= job_post.contact %></td>
        <td><%= job_post.salary %></td><br>
        <% if can? :manage, Admin %>
                <td><%= link_to 'Show', job_post %></td>
                <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
                <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
        <% end -%>
        <% if current_user.type == 'Worker' %>
                <td><%= link_to 'Apply for job', new_apply_path %></td>
                <td><%= link_to 'Show', job_post %></td>
        <%elsif job_post.contractor == current_user %>
                <td><%= link_to 'Show', job_post %></td>
                <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
                <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end -%>
          </tr>
    <%end%>
    <%= link_to 'Back', root_path  %>
</tbody>
</table>

app/views/job_posts/new.html.erb
<h1>New Job Post</h1>

<%= render 'form', job_post: @job_post %>

<%= link_to 'Back', show_contractor_job_job_posts_path %>

app/views/job_posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  
  <strong>Title:</strong>
  <%= @job_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_post.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @job_post.contact %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job_post.salary %>
</p>

<p>
  <strong>Contractor:</strong>
  <%= @job_post.contractor_id %>
</p>

<% if current_user.type == 'Worker' %>
<%= link_to 'Back', job_posts_path %>
<% elsif current_user.type == 'Admin'%>
<%= link_to 'Back', job_posts_path %>
<%= link_to 'Edit', edit_job_post_path(@job_post) %> 
<% elsif current_user.type == 'Contractor'%>
<%= link_to 'Back', show_contractor_job_job_posts_path %>
<%= link_to 'Edit', edit_job_post_path(@job_post) %> |
|<% end %>

app/views/job_posts/show_contractor_job.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Posts</h1>

<table>
  <thead>
    <tr>
       <th>Title</th>
      <th>Description</th>
      <th>Contact</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_posts.each do |job_post| %>
     <%if job_post.contractor == current_user %>
       <tr>   
        <td><%= job_post.title %></td>
        <td><%= job_post.description %></td>
        <td><%= job_post.contact %></td>
        <td><%= job_post.salary %></td><br>
        <td><%= link_to 'Show', job_post  %></td>
        <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
        <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
      <%end%>
    <%end%>
    <br>
    <%= link_to 'New Job Post', new_job_post_path %>
    <br>
    <%= link_to 'Back', root_path %>     
</tbody>
</table>